// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || import.meta.env.VITE_SUPABASE_ANON_KEY;

// Validate environment variables
if (!SUPABASE_URL) {
  console.error('Missing VITE_SUPABASE_URL environment variable');
}

if (!SUPABASE_ANON_KEY) {
  console.error('Missing VITE_SUPABASE_PUBLISHABLE_KEY or VITE_SUPABASE_ANON_KEY environment variable');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || '',
  SUPABASE_ANON_KEY || '',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'pkce',
    },
    global: {
      headers: {
        'X-Client-Info': 'pensum-manager',
      },
    },
    db: {
      schema: 'public',
    },
    // Retry configuration for better reliability
    realtime: {
      params: {
        eventsPerSecond: 10,
      },
    },
  }
);

// Helper function to check if user is authenticated
export async function isAuthenticated(): Promise<boolean> {
  const { data: { session } } = await supabase.auth.getSession();
  return !!session;
}

// Helper function to get current user ID safely
export async function getCurrentUserId(): Promise<string | null> {
  const { data: { session } } = await supabase.auth.getSession();
  return session?.user?.id ?? null;
}

// Helper to handle Supabase errors consistently
export interface SupabaseResult<T> {
  data: T | null;
  error: string | null;
}

// Check if error is a "not found" error (which is often expected)
export function isNotFoundError(error: unknown): boolean {
  if (!error || typeof error !== 'object') return false;
  const err = error as { code?: string };
  return err.code === 'PGRST116';
}

export function handleSupabaseError(error: unknown): string {
  if (!error) return 'Error desconocido';

  if (typeof error === 'object' && error !== null) {
    const err = error as { message?: string; code?: string };

    // Handle specific error codes
    // Note: PGRST116 means no rows returned - often not a true "error" but expected behavior
    if (err.code === 'PGRST116') {
      return ''; // Return empty string - this is often expected, not an error
    }
    if (err.code === '23505') {
      return 'Este registro ya existe';
    }
    if (err.code === '23503') {
      return 'No se puede eliminar porque tiene registros relacionados';
    }
    if (err.code === '42501') {
      return 'No tienes permisos para realizar esta acción';
    }

    if (err.message) {
      // Translate common error messages
      if (err.message.includes('JWT expired')) {
        return 'Tu sesión ha expirado. Inicia sesión nuevamente.';
      }
      if (err.message.includes('network')) {
        return 'Error de conexión. Verifica tu internet.';
      }
      if (err.message.includes('Failed to fetch')) {
        return 'Error de conexión. Verifica tu internet.';
      }
      return err.message;
    }
  }

  return 'Ha ocurrido un error. Intenta de nuevo.';
}

// Wrapper for database operations with better error handling
export async function safeQuery<T>(
  queryFn: () => Promise<{ data: T | null; error: unknown }>
): Promise<SupabaseResult<T>> {
  try {
    const { data, error } = await queryFn();

    if (error) {
      return { data: null, error: handleSupabaseError(error) };
    }

    return { data, error: null };
  } catch (error) {
    return { data: null, error: handleSupabaseError(error) };
  }
}